--------------------------------------------------------
--  파일이 생성됨 - 금요일-12월-12-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_BOARD_NUM
--------------------------------------------------------

   CREATE SEQUENCE  "WEBPROJECT_DB"."SEQ_BOARD_NUM"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 129 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_COMMENTS_CNUM
--------------------------------------------------------

   CREATE SEQUENCE  "WEBPROJECT_DB"."SEQ_COMMENTS_CNUM"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 86 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SEQ_FAVORITE_NUM
--------------------------------------------------------

   CREATE SEQUENCE  "WEBPROJECT_DB"."SEQ_FAVORITE_NUM"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 85 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table BOARD
--------------------------------------------------------

  CREATE TABLE "WEBPROJECT_DB"."BOARD" 
   (	"PNUM" VARCHAR2(10 BYTE), 
	"ID" VARCHAR2(10 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" VARCHAR2(2000 BYTE), 
	"POSTDATE" DATE DEFAULT sysdate, 
	"VISITCOUNT" NUMBER(6,0) DEFAULT 0, 
	"OFILE" VARCHAR2(200 BYTE), 
	"SFILE" VARCHAR2(200 BYTE), 
	"CATEGORY" VARCHAR2(30 BYTE), 
	"LIKECOUNT" NUMBER(6,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMMENTS
--------------------------------------------------------

  CREATE TABLE "WEBPROJECT_DB"."COMMENTS" 
   (	"CNUM" VARCHAR2(10 BYTE), 
	"PNUM" VARCHAR2(10 BYTE), 
	"ID" VARCHAR2(10 BYTE), 
	"CONTENT" VARCHAR2(1000 BYTE), 
	"REGIDATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FAVORITE
--------------------------------------------------------

  CREATE TABLE "WEBPROJECT_DB"."FAVORITE" 
   (	"FNUM" VARCHAR2(10 BYTE), 
	"PNUM" VARCHAR2(10 BYTE), 
	"ID" VARCHAR2(10 BYTE), 
	"REGIDATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "WEBPROJECT_DB"."MEMBER" 
   (	"ID" VARCHAR2(10 BYTE), 
	"PASSWORD" VARCHAR2(10 BYTE), 
	"NAME" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"REGIDATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into WEBPROJECT_DB.BOARD
SET DEFINE OFF;
Insert into WEBPROJECT_DB.BOARD (PNUM,ID,TITLE,CONTENT,POSTDATE,VISITCOUNT,OFILE,SFILE,CATEGORY,LIKECOUNT) values ('128','aa','ㅇㄴㅁㄹ','ㄹㅇㄴㅁㄹ',to_date('25/12/12','RR/MM/DD'),1,'br-netscape.png','20251212_10374780.png','data',0);
Insert into WEBPROJECT_DB.BOARD (PNUM,ID,TITLE,CONTENT,POSTDATE,VISITCOUNT,OFILE,SFILE,CATEGORY,LIKECOUNT) values ('112','aa','1111','1111',to_date('25/12/12','RR/MM/DD'),0,null,null,'free',0);
Insert into WEBPROJECT_DB.BOARD (PNUM,ID,TITLE,CONTENT,POSTDATE,VISITCOUNT,OFILE,SFILE,CATEGORY,LIKECOUNT) values ('113','aa','2222','2222',to_date('25/12/12','RR/MM/DD'),0,null,null,'free',0);
Insert into WEBPROJECT_DB.BOARD (PNUM,ID,TITLE,CONTENT,POSTDATE,VISITCOUNT,OFILE,SFILE,CATEGORY,LIKECOUNT) values ('114','aa','3333','3333',to_date('25/12/12','RR/MM/DD'),0,null,null,'free',0);
Insert into WEBPROJECT_DB.BOARD (PNUM,ID,TITLE,CONTENT,POSTDATE,VISITCOUNT,OFILE,SFILE,CATEGORY,LIKECOUNT) values ('115','aa','4444','4444',to_date('25/12/12','RR/MM/DD'),1,null,null,'free',0);
Insert into WEBPROJECT_DB.BOARD (PNUM,ID,TITLE,CONTENT,POSTDATE,VISITCOUNT,OFILE,SFILE,CATEGORY,LIKECOUNT) values ('116','aa','555','555',to_date('25/12/12','RR/MM/DD'),0,null,null,'free',0);
Insert into WEBPROJECT_DB.BOARD (PNUM,ID,TITLE,CONTENT,POSTDATE,VISITCOUNT,OFILE,SFILE,CATEGORY,LIKECOUNT) values ('117','aa','6666','6666',to_date('25/12/12','RR/MM/DD'),0,null,null,'free',0);
Insert into WEBPROJECT_DB.BOARD (PNUM,ID,TITLE,CONTENT,POSTDATE,VISITCOUNT,OFILE,SFILE,CATEGORY,LIKECOUNT) values ('118','aa','7777','7777',to_date('25/12/12','RR/MM/DD'),0,null,null,'free',0);
Insert into WEBPROJECT_DB.BOARD (PNUM,ID,TITLE,CONTENT,POSTDATE,VISITCOUNT,OFILE,SFILE,CATEGORY,LIKECOUNT) values ('119','bb','888','888',to_date('25/12/12','RR/MM/DD'),0,null,null,'free',0);
Insert into WEBPROJECT_DB.BOARD (PNUM,ID,TITLE,CONTENT,POSTDATE,VISITCOUNT,OFILE,SFILE,CATEGORY,LIKECOUNT) values ('120','bb','999','9999',to_date('25/12/12','RR/MM/DD'),1,null,null,'free',0);
Insert into WEBPROJECT_DB.BOARD (PNUM,ID,TITLE,CONTENT,POSTDATE,VISITCOUNT,OFILE,SFILE,CATEGORY,LIKECOUNT) values ('121','bb','10','10',to_date('25/12/12','RR/MM/DD'),1,null,null,'free',0);
Insert into WEBPROJECT_DB.BOARD (PNUM,ID,TITLE,CONTENT,POSTDATE,VISITCOUNT,OFILE,SFILE,CATEGORY,LIKECOUNT) values ('122','dd','11111111111','1111111111111',to_date('25/12/12','RR/MM/DD'),1,null,null,'free',0);
Insert into WEBPROJECT_DB.BOARD (PNUM,ID,TITLE,CONTENT,POSTDATE,VISITCOUNT,OFILE,SFILE,CATEGORY,LIKECOUNT) values ('123','dd','12121212','12121212',to_date('25/12/12','RR/MM/DD'),1,null,null,'free',0);
Insert into WEBPROJECT_DB.BOARD (PNUM,ID,TITLE,CONTENT,POSTDATE,VISITCOUNT,OFILE,SFILE,CATEGORY,LIKECOUNT) values ('124','dd','13131','131313',to_date('25/12/12','RR/MM/DD'),1,null,null,'qna',1);
Insert into WEBPROJECT_DB.BOARD (PNUM,ID,TITLE,CONTENT,POSTDATE,VISITCOUNT,OFILE,SFILE,CATEGORY,LIKECOUNT) values ('125','aa','사진','사진',to_date('25/12/12','RR/MM/DD'),1,'9.jpg','20251212_103246834.jpg','data',0);
Insert into WEBPROJECT_DB.BOARD (PNUM,ID,TITLE,CONTENT,POSTDATE,VISITCOUNT,OFILE,SFILE,CATEGORY,LIKECOUNT) values ('126','aa','동영상','동영상',to_date('25/12/12','RR/MM/DD'),1,'video.mp4','20251212_10329693.mp4','data',0);
Insert into WEBPROJECT_DB.BOARD (PNUM,ID,TITLE,CONTENT,POSTDATE,VISITCOUNT,OFILE,SFILE,CATEGORY,LIKECOUNT) values ('127','aa','음원','음원',to_date('25/12/12','RR/MM/DD'),0,'My_Love.mp3','20251212_103220722.mp3','data',0);
REM INSERTING into WEBPROJECT_DB.COMMENTS
SET DEFINE OFF;
Insert into WEBPROJECT_DB.COMMENTS (CNUM,PNUM,ID,CONTENT,REGIDATE) values ('74','124','dd','111',to_date('25/12/12','RR/MM/DD'));
Insert into WEBPROJECT_DB.COMMENTS (CNUM,PNUM,ID,CONTENT,REGIDATE) values ('75','124','dd','222',to_date('25/12/12','RR/MM/DD'));
Insert into WEBPROJECT_DB.COMMENTS (CNUM,PNUM,ID,CONTENT,REGIDATE) values ('76','124','dd','333',to_date('25/12/12','RR/MM/DD'));
Insert into WEBPROJECT_DB.COMMENTS (CNUM,PNUM,ID,CONTENT,REGIDATE) values ('77','124','dd','444',to_date('25/12/12','RR/MM/DD'));
Insert into WEBPROJECT_DB.COMMENTS (CNUM,PNUM,ID,CONTENT,REGIDATE) values ('78','124','dd','555',to_date('25/12/12','RR/MM/DD'));
Insert into WEBPROJECT_DB.COMMENTS (CNUM,PNUM,ID,CONTENT,REGIDATE) values ('79','124','dd','666',to_date('25/12/12','RR/MM/DD'));
Insert into WEBPROJECT_DB.COMMENTS (CNUM,PNUM,ID,CONTENT,REGIDATE) values ('80','124','dd','777',to_date('25/12/12','RR/MM/DD'));
Insert into WEBPROJECT_DB.COMMENTS (CNUM,PNUM,ID,CONTENT,REGIDATE) values ('81','124','dd','888',to_date('25/12/12','RR/MM/DD'));
Insert into WEBPROJECT_DB.COMMENTS (CNUM,PNUM,ID,CONTENT,REGIDATE) values ('82','124','dd','999',to_date('25/12/12','RR/MM/DD'));
Insert into WEBPROJECT_DB.COMMENTS (CNUM,PNUM,ID,CONTENT,REGIDATE) values ('83','124','dd','101010',to_date('25/12/12','RR/MM/DD'));
Insert into WEBPROJECT_DB.COMMENTS (CNUM,PNUM,ID,CONTENT,REGIDATE) values ('84','124','aa','121212',to_date('25/12/12','RR/MM/DD'));
REM INSERTING into WEBPROJECT_DB.FAVORITE
SET DEFINE OFF;
Insert into WEBPROJECT_DB.FAVORITE (FNUM,PNUM,ID,REGIDATE) values ('84','124','aa',to_date('25/12/12','RR/MM/DD'));
REM INSERTING into WEBPROJECT_DB.MEMBER
SET DEFINE OFF;
Insert into WEBPROJECT_DB.MEMBER (ID,PASSWORD,NAME,EMAIL,PHONE,REGIDATE) values ('aa','5ONme6Qu3l','홍길동','yhyh5926@naver.com','010-1111-1111',to_date('25/12/08','RR/MM/DD'));
Insert into WEBPROJECT_DB.MEMBER (ID,PASSWORD,NAME,EMAIL,PHONE,REGIDATE) values ('bb','1234','김철수','kim@naver.com','010-2222-2222',to_date('25/12/08','RR/MM/DD'));
Insert into WEBPROJECT_DB.MEMBER (ID,PASSWORD,NAME,EMAIL,PHONE,REGIDATE) values ('cc','1234','이영희','lee@naver.com','010-3333-3333',to_date('25/12/08','RR/MM/DD'));
Insert into WEBPROJECT_DB.MEMBER (ID,PASSWORD,NAME,EMAIL,PHONE,REGIDATE) values ('dd','1234','박민수','park@naver.com','010-4444-4444',to_date('25/12/08','RR/MM/DD'));
Insert into WEBPROJECT_DB.MEMBER (ID,PASSWORD,NAME,EMAIL,PHONE,REGIDATE) values ('ee','1234','최지현','choi@naver.com','010-5555-5555',to_date('25/12/08','RR/MM/DD'));
Insert into WEBPROJECT_DB.MEMBER (ID,PASSWORD,NAME,EMAIL,PHONE,REGIDATE) values ('qq','1234','김민수','kim2@naver.com','010-6666-6666',to_date('25/12/08','RR/MM/DD'));
Insert into WEBPROJECT_DB.MEMBER (ID,PASSWORD,NAME,EMAIL,PHONE,REGIDATE) values ('zz','1234','김제트','zz@naver.com','010-1111-5678',to_date('25/12/11','RR/MM/DD'));
Insert into WEBPROJECT_DB.MEMBER (ID,PASSWORD,NAME,EMAIL,PHONE,REGIDATE) values ('Lee','1111','이순신','Lee@naver.com','010-1234-5678',to_date('25/12/09','RR/MM/DD'));
Insert into WEBPROJECT_DB.MEMBER (ID,PASSWORD,NAME,EMAIL,PHONE,REGIDATE) values ('hh','1234','hh','hong@gmail.com','010-1111-1111',to_date('25/12/12','RR/MM/DD'));
--------------------------------------------------------
--  DDL for Index SYS_C008581
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008581" ON "WEBPROJECT_DB"."MEMBER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008591
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008591" ON "WEBPROJECT_DB"."BOARD" ("PNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008597
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008597" ON "WEBPROJECT_DB"."COMMENTS" ("CNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008601
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008601" ON "WEBPROJECT_DB"."FAVORITE" ("FNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UNIQUE_LIKE
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."UNIQUE_LIKE" ON "WEBPROJECT_DB"."FAVORITE" ("PNUM", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008591
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008591" ON "WEBPROJECT_DB"."BOARD" ("PNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008597
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008597" ON "WEBPROJECT_DB"."COMMENTS" ("CNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008601
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008601" ON "WEBPROJECT_DB"."FAVORITE" ("FNUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UNIQUE_LIKE
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."UNIQUE_LIKE" ON "WEBPROJECT_DB"."FAVORITE" ("PNUM", "ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008581
--------------------------------------------------------

  CREATE UNIQUE INDEX "WEBPROJECT_DB"."SYS_C008581" ON "WEBPROJECT_DB"."MEMBER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."BOARD" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD" MODIFY ("POSTDATE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."BOARD" ADD PRIMARY KEY ("PNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table COMMENTS
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."COMMENTS" MODIFY ("PNUM" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."COMMENTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."COMMENTS" MODIFY ("CONTENT" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."COMMENTS" MODIFY ("REGIDATE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."COMMENTS" ADD PRIMARY KEY ("CNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FAVORITE
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."FAVORITE" MODIFY ("PNUM" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."FAVORITE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."FAVORITE" MODIFY ("REGIDATE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."FAVORITE" ADD PRIMARY KEY ("FNUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "WEBPROJECT_DB"."FAVORITE" ADD CONSTRAINT "UNIQUE_LIKE" UNIQUE ("PNUM", "ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."MEMBER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."MEMBER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."MEMBER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."MEMBER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."MEMBER" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."MEMBER" MODIFY ("REGIDATE" NOT NULL ENABLE);
  ALTER TABLE "WEBPROJECT_DB"."MEMBER" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BOARD
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."BOARD" ADD CONSTRAINT "BOARD_MEMBER_FK" FOREIGN KEY ("ID")
	  REFERENCES "WEBPROJECT_DB"."MEMBER" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMENTS
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."COMMENTS" ADD CONSTRAINT "COMMENTS_BOARD_FK" FOREIGN KEY ("PNUM")
	  REFERENCES "WEBPROJECT_DB"."BOARD" ("PNUM") ON DELETE CASCADE ENABLE;
  ALTER TABLE "WEBPROJECT_DB"."COMMENTS" ADD CONSTRAINT "COMMENTS_MEMBER_FK" FOREIGN KEY ("ID")
	  REFERENCES "WEBPROJECT_DB"."MEMBER" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FAVORITE
--------------------------------------------------------

  ALTER TABLE "WEBPROJECT_DB"."FAVORITE" ADD CONSTRAINT "FAVORITE_BOARD_FK" FOREIGN KEY ("PNUM")
	  REFERENCES "WEBPROJECT_DB"."BOARD" ("PNUM") ON DELETE CASCADE ENABLE;
  ALTER TABLE "WEBPROJECT_DB"."FAVORITE" ADD CONSTRAINT "FAVORITE_MEMBER_FK" FOREIGN KEY ("ID")
	  REFERENCES "WEBPROJECT_DB"."MEMBER" ("ID") ENABLE;
